#!/bin/bash

case "$1" in
    dra) arg="pull" ;;
    tryck) arg="push" ;;
    verkställ) arg="commit" ;;
    klona) arg="clone" ;;
    läge) arg="status" ;;
    addera) arg="add" ;;
    *) arg=$1 ;;
esac

case "$#" in
	0) git ;;
	1) git $arg ;;
	*) git $arg "${@:2}" ;; 
esac
